-- Create notes table for channel notes
create table public.notes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  channel_id text null,
  note_content text null,
  updated_at timestamp with time zone null default now(),
  constraint notes_pkey primary key (id),
  constraint notes_channel_id_fkey foreign KEY (channel_id) references channels (channel_id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- Create index on channel_id for better performance
create index idx_notes_channel_id on public.notes (channel_id);

-- Enable RLS (Row Level Security)
alter table public.notes enable row level security;

-- Create policy to allow authenticated users to manage notes
create policy "Enable all operations for authenticated users" on public.notes
for all using (auth.role() = 'authenticated');
